export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const LOGOUT_ERROR = 'LOGOUT_ERROR'
export const SIGNUP = 'SIGNUP'
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE'
export const CONFIRMATION = 'CONFIRMATION'
export const RESET_PASSWORD = 'RESET_PASSWORD'